# Builds LWJGL and runs tests.
# No artifacts are uploaded, see LWJGL-CI/lwjgl3 for that.
name: LWJGL Build

on:
  workflow_dispatch:
  push:
    branches:
      - riscv-ci-builds

env:
  ANT_OPTS: -Xmx1G
  LWJGL_BUILD_TYPE: nightly

jobs:
  linux-riscv64:
    name: Linux riscv64 Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ARCH: [riscv64]
        include:
          # ----
          - ARCH: riscv64
            CROSS_ARCH: riscv64
            TRIPLET: riscv64-linux-gnu
    env:
      LWJGL_BUILD_ARCH: ${{matrix.ARCH}}
      JAVA_HOME: /usr/lib/jvm/openjdk-21/
      JAVA8_HOME: /usr/lib/jvm/openjdk-21/ # Not actually required to be java 8, as it only makes sure no new features are used
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 3
          ref: 'f0ec1437a6149dae00eaa27c47268e5e4efb129f'
      - name: Apply riscv patches # necessary for RISC-V
        if: matrix.ARCH == 'riscv64'
        run: |
          curl -L https://raw.githubusercontent.com/Vixea/lwjgl-riscv-patches/refs/heads/master/diff.patch >> diff.patch
          git apply diff.patch
      - uses: uraimo/run-on-arch-action@v3
        with:
          arch: riscv64
          distro: ubuntu24.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${{ github.workspace }}"
          install: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y default-jdk git ant curl zstd make gcc-12 g++-12 libc6-dev
            DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk-3-dev libatk-bridge2.0-dev libgdk-pixbuf2.0-dev libglu-dev libx11-dev libxt-dev libdbus-1-dev # libgl1-mesa-glx
          run: |
            git config --global --add safe.directory $(pwd)
            ANT_OPTS=-Xmx4G ant -emacs compile-templates -Dbackend-threads=0
            ant -emacs clean-generated generate
            ant -emacs compile
            JAVA8_HOME=/usr/lib/jvm/openjdk-21/ ant -emacs compile-native -Dgcc.version=12 -Dgcc.version.print=true -Dgcc.libpath.opengl=/usr/lib/${{matrix.TRIPLET}}/mesa
            JAVA8_HOME=/usr/lib/jvm/openjdk-21/ LWJGL_BUILD_OFFLINE=true ant -emacs release -Dgcc.version=12 -Dgcc.version.print=true -Dgcc.libpath.opengl=/usr/lib/${{matrix.TRIPLET}}/mesa
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: ./bin/RELEASE/*